// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDilPRUc-FGaHqsojMywybwgwhD-e5mMwU',
    appId: '1:138611642208:web:da89f1ed7b46e7a127d805',
    messagingSenderId: '138611642208',
    projectId: 'bobsponja-3af29',
    authDomain: 'bobsponja-3af29.firebaseapp.com',
    storageBucket: 'bobsponja-3af29.appspot.com',
    measurementId: 'G-ZRHS15HQ8D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnmr0zAOfc1axg5v3lMsLUWITUQ-LARKQ',
    appId: '1:138611642208:android:6c4b1a61ff671eea27d805',
    messagingSenderId: '138611642208',
    projectId: 'bobsponja-3af29',
    storageBucket: 'bobsponja-3af29.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA02zGQyrdAxHjR1ArVFxIEn45ck-VyY4w',
    appId: '1:138611642208:ios:e00f02e4f4bda22427d805',
    messagingSenderId: '138611642208',
    projectId: 'bobsponja-3af29',
    storageBucket: 'bobsponja-3af29.appspot.com',
    iosBundleId: 'com.example.flutterApplication',
  );
}
